[package]
name = "mini_sqlite_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "mini_sqlite"
path = "src/lib.rs"

[[bin]]
name = "mini_sqlite_rust"
path = "src/main.rs"
